# Generated by Django 5.1.4 on 2024-12-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
