# Generated by Django 5.1.4 on 2024-12-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_firstname_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='join_date',
            new_name='date_joined',
        ),
    ]
