# Generated by Django 5.1.2 on 2024-12-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
